### ISSUE TITLE
Printer Power module not showing

### ISSUE THREAD

**Issue by cruzer619** [ZeroGDesign/zerog-mainsail-theme#4]
Not a big issue but with the release of mainsail 2.5.0 there is a printer power module.  With this theme it doesn't show.  Without theme it shows up.

**Comment by ZeroGDesign** [comment]
Do you have a screenshot for this? This is strange because we're only adjusting the background and some fonts https://github.com/ZeroGDesign/zerog-mainsail-theme/blob/master/.theme/custom.css

**Comment by cruzer619** [comment]
![zerog-powergone](https://user-images.githubusercontent.com/26581299/227018805-b8dfb6bf-c0fe-424b-9040-9c046c229398.JPG)
![zerog-powerbutton](https://user-images.githubusercontent.com/26581299/227018818-7aef69f9-c8e3-4848-8f47-8fbf074e12c6.JPG)
![zerog-mainsail](https://user-images.githubusercontent.com/26581299/227018828-94d50aac-83be-4174-a911-68ef32d4ce05.JPG)

ok after playing around.. I found that it will show if I do a "firmware restart" in the machine or dashboard tab.  But only for 1 sec and then revert back to show klipper report.

**Comment by ZeroGDesign** [comment]
That seems like a mainsail issue to me

**Comment by cruzer619** [comment]
strange this time when I remove the .theme folder... now its not showing either.. ok.. thanks for the help.. will get on mainsail side.
